"""Declarative, cluster-executable trajectory power study."""

from motco.simulations.study.config import (
    AcceptanceTargets,
    AttributionSelector,
    GateRule,
    MatchedSeedPolicy,
    Phase4GateConfig,
    PowerMonotonicityTarget,
    SpecificityTarget,
    StudyConfig,
    StudyConfigError,
    TypeIControlTarget,
    dump_study_config,
    load_study_config,
)
from motco.simulations.study.enumerate import enumerate_study
from motco.simulations.study.merge import StudyMergeError, merge_shards
from motco.simulations.study.phase4 import (
    GateObservation,
    Phase4GateDecision,
    Phase4SummaryError,
    build_operating_frame,
    evaluate_phase4_gate,
    localize_off_diagonal,
    summarize_attribution,
    summarize_pls_selection,
    summarize_realized_geometry,
    type_i_inflation_bound,
)
from motco.simulations.study.report import (
    Phase4ReportFrames,
    StudyReportError,
    build_phase4_frames,
    build_power_curves,
    build_specificity_matrix,
    build_type_i_table,
    render_attribution_stability,
    render_geometry_checkpoints,
    render_phase4_figures,
    render_power_curves,
    render_selected_components,
    render_specificity_matrix,
    render_type_i_plot,
    write_phase4_report,
    write_report_csvs,
)
from motco.simulations.study.sharding import (
    StudyShardError,
    enumerate_units,
    partition_unit,
    run_shard,
)
from motco.simulations.study.summary import (
    CombinedRuleSummary,
    summarize_combined_rule,
    summarize_study,
)
from motco.simulations.study.targets import (
    TargetEvaluation,
    evaluate_targets,
    write_target_report,
)

__all__ = [
    "AcceptanceTargets",
    "AttributionSelector",
    "CombinedRuleSummary",
    "GateObservation",
    "GateRule",
    "MatchedSeedPolicy",
    "Phase4GateConfig",
    "Phase4GateDecision",
    "Phase4ReportFrames",
    "Phase4SummaryError",
    "PowerMonotonicityTarget",
    "SpecificityTarget",
    "StudyConfig",
    "StudyConfigError",
    "StudyMergeError",
    "StudyReportError",
    "StudyShardError",
    "TargetEvaluation",
    "TypeIControlTarget",
    "build_operating_frame",
    "build_phase4_frames",
    "build_power_curves",
    "build_specificity_matrix",
    "build_type_i_table",
    "dump_study_config",
    "enumerate_study",
    "enumerate_units",
    "evaluate_phase4_gate",
    "evaluate_targets",
    "load_study_config",
    "localize_off_diagonal",
    "merge_shards",
    "partition_unit",
    "render_attribution_stability",
    "render_geometry_checkpoints",
    "render_phase4_figures",
    "render_power_curves",
    "render_selected_components",
    "render_specificity_matrix",
    "render_type_i_plot",
    "run_shard",
    "summarize_attribution",
    "summarize_combined_rule",
    "summarize_pls_selection",
    "summarize_realized_geometry",
    "summarize_study",
    "type_i_inflation_bound",
    "write_phase4_report",
    "write_report_csvs",
    "write_target_report",
]
